server {
    listen 8080;
    listen 9090;
    host 0.0.0.0;
    server_name localhost:8080;
    root /home/mzanana/Desktop/Github/WebServ/www;
    index index.html;
    client_max_body_size 10000k;

    
    location / {
        autoindex off;
        allowed_methods GET;
    }

	location /upload {
		client_max_body_size 10000k;
		autoindex on;
		allowed_methods GET POST DELETE;
	}
	
	location /301 {
        return 301 /error_pages/301.html;
    }
	
	location /cgi-bin {
		autoindex on;
		allowed_methods GET POST;
		cgi_extension .py /usr/bin/python3;
		cgi_extension .php /usr/bin/php-cgi;
	}

	location /session {
		autoindex off;
		allowed_methods POST GET;
		cgi_extension .py /usr/bin/python3;
	}

    location /google {
        return 301 https://google.com;
    }

    location /custom-message {
        return 200 "Hello from the new return directive!";
    }

    error_page 400 /error_pages/400.html;
    error_page 403 /error_pages/403.html;
    error_page 404 /error_pages/404.html;
    error_page 405 /error_pages/405.html;
    error_page 408 /error_pages/408.html;
    error_page 409 /error_pages/409.html;
    error_page 410 /error_pages/410.html;
    error_page 411 /error_pages/411.html;
    error_page 413 /error_pages/413.html;
    error_page 414 /error_pages/414.html;
    error_page 415 /error_pages/415.html;
    error_page 500 /error_pages/500.html;
    error_page 502 /error_pages/502.html;
    error_page 504 /error_pages/504.html;
    error_page 505 /error_pages/505.html;
}


server {
	listen 1337;
    host 0.0.0.0;
    server_name localhost:8080;
    root /home/mzanana/Desktop/Github/WebServ/www;
    index index.html;
    client_max_body_size 10k;

    
    location / {
        autoindex off;
        allowed_methods  POST;
    }

	location /upload {
		client_max_body_size 100k;
		autoindex on;
		allowed_methods GET POST DELETE;
	}

	location /session {
		autoindex off;
		allowed_methods POST GET;
		cgi_extension .py /usr/bin/python3;
	}


    error_page 400 /error_pages/400.html;
    error_page 403 /error_pages/403.html;
    error_page 404 /error_pages/404.html;
    error_page 405 /error_pages/405.html;
    error_page 408 /error_pages/408.html;
    error_page 409 /error_pages/409.html;
    error_page 410 /error_pages/410.html;
    error_page 411 /error_pages/411.html;
    error_page 413 /error_pages/413.html;
    error_page 414 /error_pages/414.html;
    error_page 415 /error_pages/415.html;
    error_page 500 /error_pages/500.html;
    error_page 502 /error_pages/502.html;
    error_page 504 /error_pages/504.html;
    error_page 505 /error_pages/505.html;
}