server {
    listen 1027;
    host 0.0.0.0;
    server_name localhost;
    root /home/moel-aid/goinfre/new;
    index index.html;
    client_max_body_size 1000000;

    location / {
        autoindex on;
        index index.html;
        allowed_methods GET;
    }

    location /directory/Yeah/ {
        index youpi.bad_extension;
        allowed_methods GET POST;
    }

    location /directory/ {
        index youpi.bad_extension;
        allowed_methods GET POST;
    }

    location /directory_get/ {
        # root /home/salhali/Desktop/LastVersion/EngineX/www-subject-tester/YoupiBanane/;
        index youpi.bad_extension;
        allowed_methods GET;
    }

    location /directory_post/ {
        allowed_methods POST;
        cgi_extension .bla /home/moel-aid/goinfre/new/www;
    }

    error_page 404 /404.html;
    error_page 500 /500.html;
}
