server {
    listen 1027;
    host 0.0.0.0;
    server_name localhost;
    root /home/salhali/Desktop/lastversion/www/;
    index index.htm;

    location / {
        autoindex on;
        allowed_methods GET POST DELETE;
        cgi_extension .py /usr/bin/;
        


        # cgi_extension .sh /usr/bb;
    }
	
	location /directory/nop/ {
        autoindex on;
        allowed_methods GET POST DELETE;
        cgi_extension .py /usr/bin/;
        
    }
    location /directory/Yeah/ {
        autoindex on;
    }

    location /post_body {
        allowed_methods POST;
        upload_store /home/salhali/Desktop/lastversion/www/upload;
    }

    location /directory/ {
        allowed_methods GET POST;
    }

    location /directory_get/ {
        allowed_methods GET;
    }

    location /directory_post/ {
        allowed_methods POST;
        cgi_extension .bla /home/salhali/lastversion/www/cgi_tester;
    }
}
