server {
    listen 1027;
    host 127.0.0.1;
    server_name localhost;
    root /goinfre/moel-aid/Aidi/EngineX/www-subject-tester;
    index index.htm;
    autoindex on;
    client_max_body_size 105m;

    location / {
        index index.htm;
        allowed_methods GET;
    }

    location /post_body {
        client_max_body_size 100;
        allowed_methods POST;
    }

    location /directory/ {
        index youpi.bad_extension;
        allowed_methods GET POST;
        cgi_extension .bla /goinfre/moel-aid/Aidi/EngineX/www-subject-tester/cgi_tester;
    }

    location /directory/Yeah {
        root /goinfre/moel-aid/Aidi/EngineX;
        allowed_methods GET;
    }

    location /directory/Yeah/not_happy.bad_extension {
        root /goinfre/moel-aid/Aidi/EngineX/www-subject-tester;
        allowed_methods GET;
    }
}

server {
    listen 1025;
    listen 1026;
    host 127.0.0.2;
    server_name localhost;
    root /goinfre/moel-aid/Aidi/EngineX/www;
    index index.htm;
    autoindex on;
    client_max_body_size 2k;

    location / {
        cgi_extension .py /usr/bin/python3;
    }

    location /upload {
        allowed_methods GET POST DELETE;
    }

    location /get-only {
        allowed_methods GET;
    }

    location /post-only {
        allowed_methods POST;
    }

    location /old-page {
        return 301 /new-page;
    }

    location /temp-page {
        return 302 /index.htm;
    }

    location /ext-redirect {
        return 301 http://example.com;
    }

    location /autoindex-dir {
        autoindex on;
    }

    location /no-index-dir {
        autoindex off;
    }

    location /auto-with-index {
        autoindex on;
        index index.htm;
    }

    location /mapped {
        root /goinfre/moel-aid/Aidi/EngineX/www/root-Test;
        index index.htm;
    }

    location /dir-with-index {
        root /goinfre/moel-aid/Aidi/EngineX/www;
        index index.htm;
    }

    location /cgi-bin {
        cgi_extension .py /usr/bin/python3;
        allowed_methods POST GET;
    }
}